<?php

define('CVA_GRANT_ID', 88);

/**
 * Implements hook_permission().
 */
function content_view_access_permission() {
  $perms = array();
  foreach (node_type_get_names() as $type => $name) {
    $perms += array(
      "view own $type content" => array(
        'title' => t('%type_name: View own content', array('%type_name' => $name)),
      ),
      "view any $type content" => array(
        'title' => t('%type_name: View any content', array('%type_name' => $name)),
      ),
    );
  }
  return $perms;
}

/**
 * Implements hook_node_access_records().
 */
function content_view_access_node_access_records($node) {
  $grants = array();

  if ($node->status) {
    // Give authors own realm
    $grants[] = array(
      'nid' => $node->nid,
      'realm' => 'cva_view_own_' . $node->type,
      'gid' => $node->uid,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
    $grants[] = array(
      'nid' => $node->nid,
      'realm' => 'cva_view_any_' . $node->type,
      'gid' => CVA_GRANT_ID,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
  } else {
    $grants[] = array(
      'nid' => $node->nid,
      'realm' => 'cva_view_own_unpublished_' . $node->type,
      'gid' => $node->uid,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
    $grants[] = array(
      'nid' => $node->nid,
      'realm' => 'cva_view_any_unpublished_' . $node->type,
      'gid' => CVA_GRANT_ID,
      'grant_view' => 1,
      'grant_update' => 0,
      'grant_delete' => 0,
      'priority' => 0,
    );
  }
  return $grants;
}

/**
 * Implementation of hook_node_grants().
 *
 * Returns any grants which may give the user permission to perform the
 * requested op.
 */
function content_view_access_node_grants($account, $op) {
  $grants = array();
  if ($op == 'view') {
    foreach (node_type_get_names() as $type => $name) {
      // If they're the author and have the permission
      if (user_access('view own ' . $type . ' content', $account)) {
        $grants['cva_view_own_' . $type] = array($account->uid);
      }
      if (user_access('view any ' . $type . ' content', $account)) {
        $grants['cva_view_any_' . $type] = array(CVA_GRANT_ID);
      }
      // Add integration for unpublished content.
      if ((user_access('view any unpublished content', $account)) &&
        (user_access('view any ' . $type . ' content', $account))) {
        $grants['cva_view_any_unpublished_' . $type] = array(CVA_GRANT_ID);
      }
      if ((user_access('view own unpublished content', $account)) &&
        (user_access('view own ' . $type . ' content', $account))) {
        $grants['cva_view_own_unpublished_' . $type] = array($account->uid);
      }
    }
  }
  if (count($grants)) {
    return $grants;
  }
}
